os: osx

osx_image: xcode9.4

language: cpp

#addons:
#  homebrew:
#    taps: phil-blain/homebrew-versions
#    casks: qt@5.11

install:
#  - rvm use 2.3 --install --binary
#  - brew untap homebrew/versions
#  - brew update
  - export HOMEBREW_VERBOSE_USING_DOTS=1
  - export HOMEBREW_VERBOSE=1
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - brew tap phil-blain/homebrew-versions
  # Do not cleanup automatically
  - export HOMEBREW_NO_INSTALL_CLEANUP=1
  - brew install qt@5.11
  - brew switch qt 5.11
# - brew upgrade boost
#  - brew upgrade cmake

script:
  - mkdir -p build/Release
  - cd build/Release
  - cmake -DQt5_DIR=$(brew --prefix qt)/lib/cmake/Qt5 ../..
  - make Sourcetrail


