os: osx

osx_image: xcode9.2

language: cpp

#addons:
#  homebrew:
#    taps: phil-blain/homebrew-versions
#    casks: qt@5.11

install:
#  - rvm use 2.3 --install --binary
#  - brew untap homebrew/versions
#  - brew update
  - export HOMEBREW_VERBOSE_USING_DOTS=1
#  - export HOMEBREW_NO_AUTO_UPDATE=1
  - brew tap phil-blain/homebrew-versions
  - brew install qt@5.11 --verbose
  - brew upgrade boost
  - brew upgrade cmake

script:
  - mkdir -p build/Release
  - cd build/Release
#  - cmake -DCMAKE_BUILD_TYPE="Release" -DBOOST_ROOT=/usr/local/Cellar/boost/:$(brew info boost|grep 'boost:'| awk '{print $3}'|sed -e 's/,//') -DQt5_DIR=<path/to/Qt/version/platform/compiler/lib/cmake/Qt5> ../..
  - cmake -DCMAKE_BUILD_TYPE="Release" ../.. 
  - make Sourcetrail


