os: osx

osx_image: xcode9.4

language: cpp

install:
  - export HOMEBREW_VERBOSE_USING_DOTS=1
  - export HOMEBREW_VERBOSE=1
  - export HOMEBREW_NO_AUTO_UPDATE=1
  # Do not cleanup automatically
  - export HOMEBREW_NO_INSTALL_CLEANUP=1
  # Useful for Travis debug build
  - export HOMEBREW_NO_ANALYTICS=1
  - brew tap phil-blain/homebrew-versions
  - brew install -f qt@5.11
  # Needed for bundle_install script (`convert`)
  - brew install imagemagick
  # For C/C++ support
  - brew install llvm@9
  # Make times out, let's try ninja
  - brew install ninja

script:
  - export MACOSX_DEPLOYMENT_TARGET=10.11
  - mkdir -p build/Release
  - cd build/Release
  - cmake -G "Ninja" -DQt5_DIR=$(brew --prefix qt)/lib/cmake/Qt5 -DBUILD_CXX_LANGUAGE_PACKAGE=ON -DClang_DIR=$(brew --prefix llvm@9)/lib/cmake/clang ../..
  - ninja -v
  - ./app/bundle_install.sh
  - mkdir deploy
  - mv app/Sourcetrail*.zip deploy/Sourcetrail.zip
  - mv app/Sourcetrail*.dmg deploy/Sourcetrail.dmg
  - cd ../..
