os: osx

osx_image: xcode9.4

language: cpp

#addons:
#  homebrew:
#    taps: phil-blain/homebrew-versions
#    casks: qt@5.11

install:
#  - rvm use 2.3 --install --binary
#  - brew untap homebrew/versions
#  - brew update
  - export HOMEBREW_VERBOSE_USING_DOTS=1
  - export HOMEBREW_VERBOSE=1
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - brew tap phil-blain/homebrew-versions
  # Do not cleanup automatically
  - export HOMEBREW_NO_INSTALL_CLEANUP=1
  # Useful for Travis debug build
  - export HOMEBREW_NO_ANALYTICS=1
  - brew install -f qt@5.11
# - brew upgrade boost
#  - brew upgrade cmake
  # Needed for bundle_install script (`convert`)
  - brew install imagemagick
  # For C/C++ support
  - brew install llvm@9
  # Make times out, let's try ninja
  - brew install ninja

script:
  - mkdir -p build/Release
  - cd build/Release
  - cmake -G "Ninja" -DQt5_DIR=$(brew --prefix qt)/lib/cmake/Qt5 -DBUILD_CXX_LANGUAGE_PACKAGE=ON -DClang_DIR=$(brew --prefix llvm@9)/lib/cmake/clang ../..
#  - make -j Sourcetrail VERBOSE=1
  - ninja -v
  - ./app/bundle_install.sh


