os: osx

osx_image: xcode9.4

language: cpp

#addons:
#  homebrew:
#    taps: phil-blain/homebrew-versions
#    casks: qt@5.11

install:
#  - rvm use 2.3 --install --binary
#  - brew untap homebrew/versions
#  - brew update
  - export HOMEBREW_VERBOSE_USING_DOTS=1
  - export HOMEBREW_VERBOSE=1
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - brew tap phil-blain/homebrew-versions
  # Do not cleanup automatically
  - export HOMEBREW_NO_INSTALL_CLEANUP=1
  # Useful for Travis debug build
  - export HOMEBREW_NO_ANALYTICS=1
  - brew install -f qt@5.11
# - brew upgrade boost
#  - brew upgrade cmake
  # Needed for bundle_install script (`convert`)
  - brew install imagemagick
  # For C/C++ support
  - brew install llvm@9
  # Make times out, let's try ninja
  - brew install ninja

script:
  - mkdir -p build/Release
  - cd build/Release
  - cmake -G "Ninja" -DQt5_DIR=$(brew --prefix qt)/lib/cmake/Qt5 -DBUILD_CXX_LANGUAGE_PACKAGE=ON -DClang_DIR=$(brew --prefix llvm@9)/lib/cmake/clang ../..
#  - make -j Sourcetrail VERBOSE=1
  - ninja -v
  - ./app/bundle_install.sh
  - mkdir deploy
  - mv app/Sourcetrail*.zip deploy
  - mv app/Sourcetrail*.dmg deploy

deploy:
  provider: releases
  file_glob: true
  file: build/Release/deploy/*
  skip_cleanup: true
  draft: true
  overwrite: true
  api_key:
    secure: BIh//Q1pmwQo+ibnFfNuupAurD1hcoVvj2gtdjkKy3MDD29NsKQXnIzMjrQCXwOwax6Junxwxs7qh8fIVlUg7FmsPqCiz2n57ifp+bjIOMKA6WV3S2ec6YL9yW9jmNzGvYPeL2hH21UGNGp4YClW+jUA/OkqTATOP5Cc0wPhLgif4/AasIWvnSLoy2R147zZ9QpezJp80qtRO/T8294ugp5qulEtAXiFN8I8nLBRpF2zAGxUQRyySwnT7/HQXgzXC5zThOqPWFoRgNne9BJqAt5YpNs6K9LGhV1hwQ3Z//ENX4J7ATSkaRBXElbryGz9jNgfUu1e+tnt3Ub9Bub8QDr9JUVvvXJa/LhvyJBILjGfF+2z3tR2ylvVAIKp4QbLU29ao6JLAl32gA207v84ZTTslwV37yjbOY1bI4BTy6eFfOidRLz1g+80gxMU8KSYUkHo+3DoOM6Jc0lBNrdhJi/BQ8bTNexX8BLCqjAaG6Tdt5LjSQucrQH3zm+yG65Fv6VKJ8Llp72eBn8VT5YdGlUHSy6tPL4fDXE/ztpu+1obNDYMHF07BuB0nR6mZDpU4gyTCbRRxKwmr2kuprw95+PrfRD+mWtCfT0LfVja7XGcBUJaEjMgT6m/nHwF6s6t1YugX5jcyBvBmfevgM7/dq30FXugm5XbcgPh6ordfn8=
  on:
    tags: true
